{% set version = "1.8.4" %}

package:
  name: pytorch-3dunet
  version: {{ version }}

source:
  url: https://github.com/wolny/pytorch-3dunet/archive/refs/tags/{{ version }}.tar.gz
  sha256: 563d399399ac944d2355061ed5b11067e73b576688a4c183d51d71e55730e4ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - predict3dunet = pytorch3dunet.predict:main
    - train3dunet = pytorch3dunet.train:main

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - pytorch
    - tensorboard
    - tqdm
    - h5py
    - scipy
    - scikit-image
    - pyyaml

test:
  imports:
    - pytorch3dunet
    - pytorch3dunet.unet3d
    - pytorch3dunet.augment
    - pytorch3dunet.datasets
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/wolny/pytorch-3dunet
  summary: 'Versatile U-Net implementation for volumetric semantic segmentation written in PyTorch'
  description: |
    PyTorch implementation of 3D U-Net and its variants (ResidualUNet3D, ResidualUNetSE3D).
    The code allows for training the U-Net for both: semantic segmentation (binary and multi-class) 
    and regression problems (e.g. de-noising, learning deconvolutions).
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/wolny/pytorch-3dunet
  dev_url: https://github.com/wolny/pytorch-3dunet

extra:
  recipe-maintainers:
    - wolny
